### ISSUE TITLE
User defined SluggableBehavior

### ISSUE THREAD

**Issue by davidnewcomb** [bizley/yii2-podium#102]
My thread titles have a lot of slashes and the occasional Unicode character and when the default ``SluggableBehavior`` has finished the slug is a mumbled mess.

I would really like to do my own formatting but the ``SluggableBehavior`` declarations are buried inside your custom ``ActiveRecord`` classes and not easy to get to without a lot of overriding.

**Comment by bizley** [comment]
What kind of SluggableBehavior configuration would you like to use in this case?

**Comment by davidnewcomb** [comment]
The default behaviour of SluggableBehavior is to strip out slashes ("/") but I would like them to be converted to minus ("-"). My thread names are linked to a path so when all the separators are removed it looks a bit meaningless.

If you create a new type called PodiumSluggableBehavior which extends SluggableBehavior then you could use that in ThreadActiveRecord.behavior(), etc. You can still update the $attribute for backward compatibility. Then you could override generateSlug() which uses an implementation specified in the config.

Alternatively just allow us to specify our implementation of SluggableBehavior. Maybe you could expand it so that we implement thread slugs differently from category slugs, etc.

Just thinking allowed but I can see some organisations wanting to have their own format.

**Comment by bizley** [comment]
Thanks for PR!
