### ISSUE TITLE
I do not work sorting in forums.

### ISSUE THREAD

**Issue by zikwall** [bizley/yii2-podium#108]
I do not work sorting in forums, I click on "Hot topics" and nothing happens, but if you manually register forum.foo /forum/1/1/alias/(  hot  ) at least, everything is fine...

**Comment by bizley** [comment]
You mean "Hot Threads"? Are you sure it's not working? When there are no threads the only difference between showing everything and only hot threads is the message displayed - for all it's `No threads have been added yet.` and for hot it's `No threads matching the filters can be found.`

If this is not the case check browser's console for JS errors. If nothing interesting is there send me your application configuration.

**Comment by zikwall** [comment]
I worked on a **local server** and the problem was this, I do not know why, probably there was not enough "speed" for the server's response, so the filtering did not work. In the console, too, there were no problems.

In general, the problem is solved with the **transfer to the server**, everything is working there. An annoying mistake ...) Maybe someone will come in handy this decision.

Thanks for the response and for your forum module - just a great project!
