### ISSUE TITLE
Podium issue when installation

### ISSUE THREAD

**Issue by tanveer2030** [bizley/yii2-podium#124]
![podium](https://user-images.githubusercontent.com/12453767/27351082-9b8460a8-5615-11e7-8afa-0268215fa7ea.png)

I am facing this issue when i tried to install podium in my exiting yii2-advanced application and below is my composer.json file content.

"require": {
        "php": ">=5.4.0",
        "yiisoft/yii2": ">=2.0.6",
        "yiisoft/yii2-bootstrap": "*",
        "yiisoft/yii2-swiftmailer": "*",
        "yiidoc/yii2-redactor" : "*",
        "stripe/stripe-php": "3.*",
        "yiisoft/yii2-authclient": "*",
        "nickcv/yii2-mandrill": "*",
        "kartik-v/yii2-mpdf": "*",
        "bizley/podium": "^0.7.0",
        "bizley/quill": "^2.0"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },

It would be great if someone will help me.

Thanks

**Comment by bizley** [comment]
Please show me your `/frontend/config/main.php` file or any other relevant config file.

**Comment by tanveer2030** [comment]
Thank you so much for your response. Please have a look at below.

`

$params = array_merge(
    require(__DIR__ . '/../../common/config/params.php'),
    require(__DIR__ . '/../../common/config/params-local.php'),
    require(__DIR__ . '/params.php'),
    require(__DIR__ . '/params-local.php')
);

return [
    'id' => 'app-frontend',
    'defaultRoute' => 'site',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'LastLogin', 'campfire'],
    'controllerNamespace' => 'frontend\controllers',
    'components' => [
        
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        
        'user' => [
            'identityClass' => 'common\models\User',
            'enableAutoLogin' => true,
            'loginUrl' => ['user/login'],
        ],
        'log' => [
            'traceLevel' => YII_DEBUG ? 3 : 0,
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'errorHandler' => [
            'errorAction' => 'site/error',
        ],
        
        'assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => [
                    'sourcePath' => null,
                    'basePath' => '@webroot',
                    'baseUrl' => '@web',
                    'js' => [
                        'js/jquery.js',
                    ]
                ],
            ],
        ],
        
        'LastLogin' => [
            'class' => 'frontend\components\LastLogin'
        ],
        'campfire' => [
            'class' => 'bizley\podium\Podium',
            'userComponent' => 'user',
            'id' => 1,
        ]
    ],
    'params' => $params,
];
`

**Comment by bizley** [comment]
As explained in the [Installation guide](https://github.com/bizley/yii2-podium/wiki/1.-Installation) you should put the module configuration in the `modules` section - right now it's in `components`.

And there is `id` in your Podium config - I strongly believe it should be `adminId` 😉

**Comment by tanveer2030** [comment]
Thank you so much
