### ISSUE TITLE
getting podium to work with webivmark user management?

### ISSUE THREAD

**Issue by Wyveres** [bizley/yii2-podium#137]
is there any way to use the user management provided by webvimark together with podium, and not use the podium user and role?

**Comment by bizley** [comment]
I'm not familiar with https://github.com/webvimark/user-management so I'm not sure if it's possible. But for sure you can use [outside RBAC component](https://github.com/bizley/yii2-podium/wiki/2.-Advanced-Installation#rbac-component).
