### ISSUE TITLE
Проблема после установки

### ISSUE THREAD

**Issue by kaunnikov** [bizley/yii2-podium#139]
Установил чистый yii2 basic, сделал всё согласно инструкции - установилось, всё отлично, НО: не получается авторизоваться, admin/admin и просто выбрасывает на главную форума, без ошибок и оповещений, не могу найти причину. Далее установил из zip архива - всё работает отлично, но там есть баг, если название форума (ветки) вводить на русском языке, то ссылка получается кривая, перейти туда невозможно, ссылка выглядит приблизительно следующим образом: podium/forum/thread?cid=1&fid=1&id=1&slug=
slug остается пустой, не генерируется. Если вводить на английском - всё ок, но нужен форум для русскоязычных.

И еще есть вопрос: какие есть способы кастомизации этого модуля? Если я хочу изменить view, кроме как редактирования в папке vendor нет других вариантов? 
Также хочу добавить авторизацию/регистрацию через соцсети - изменять всё в venor?
@bizley

**Comment by bizley** [comment]
I'm not developing this anymore, I'm working on the new version.

As for your questions:
- I'm not sure about the installation bug, usually it's about misconfiguration, other packages conflict or server/db version.
- If slug is not generated maybe there is no `intl` library installed in your system?
- You can change the views by adding your own theme, see [Theming](https://www.yiiframework.com/doc/guide/2.0/en/output-theming) in the Guide.
- Social media login is not supported. You can add it by extending the module with your own classes. Never modify vendor files though, all changes will be lost at update process.
