### ISSUE TITLE
Use markdown instead of WYSIWYG

### ISSUE THREAD

**Issue by samdark** [bizley/yii2-podium#17]
It's easier to write markdown. Cleaner code is produced, it's easy to get code highlighting etc.

See demo here: http://rmcreative.ru/playground/codemirror/ (try php and JS code blocks, github-flavored markdown, typing `@`, buttons).

**Comment by bizley** [comment]
I've thought about it when looking for a good editor (and I've seen a LOT of them) and I really like markdown but the main problem with it is it's not that obvious as typical wysiwyg and this might be uncomfortable for users (or not? Am I too harsh here?)

Still, markdown editor may be a good option to add.

**Comment by samdark** [comment]
From my experience, non-tech people are OK with markdown.

**Comment by bizley** [comment]
Just curious - what are you using to convert markdown code to html?

**Comment by samdark** [comment]
Carsten's GFM-flavored markdown library which is used by default Yii markdown helper.

**Comment by samdark** [comment]
I've released parts of the demo above as CodeMirror addons:
- https://github.com/samdark/codemirror-autosuggest
- https://github.com/samdark/codemirror-buttons

**Comment by jacmoe** [comment]
[NodeBB](https://github.com/NodeBB/NodeBB) has Markdown as the default editor, so I think that it would be the perfect choice of editor also for non-tech people.

**Comment by GaikaGroup** [comment]
If you have any plans for the product to be used by people (instead of programmers) get rid of markdown immediately & implement WYSIWYG.

**Comment by bizley** [comment]
I'm actually planning to get both. For admin to choose.

**Comment by jacmoe** [comment]
> If you have any plans for the product to be used by people (instead of programmers) get rid of markdown immediately & implement WYSIWYG.

What a ridiculous comment!
Good old phpBB  have powered huge communities for ages, using plain text and bbcode.
Plain text, bbcode and perhaps Markdown is far more common than allowing HTML.
Or even using WYSIWYG editors.
I believe that both Discourse and NodeBB only enables HTML if the admin allows it.
And while you can get a WYSIWYG editor plugin for NodeBB, I am not sure about Discourse..

Yes, IPBoard does feature a visual editor - and it is horrible!
But all other serious forum software leans heavily towards plain text with minimal markup.

**Comment by samdark** [comment]
BBCode is classics and I remember people were having more trouble using it than markdown.

**Comment by samdark** [comment]
As admins we were turning off IPBoard visual editor right away. Did that for about 5 huge forum-powered communities back in the days. Noone complained.

**Comment by bizley** [comment]
It's true about bbcode - it was very popular back then and people used it without problems.
I guess markdown is like a modern version of bbcode now.

Anyway - I'm keeping Quill as it is. I'm quite happy with the way it works and produce not-that-messy html as other wysiwygs.
I'm working on the option to replace Quill with markdown editor as an option for Administrator. This way everyone should be happy.

**Comment by bizley** [comment]
I keep this open untill 0.6.

**Comment by bizley** [comment]
Released with 0.6
