### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by Felli** [bizley/yii2-podium#2]
Maybe adding a way of contacting you other than Github issues & plug pulls because I'd really like to see if I'd be able to implement this into a Module for Humhub when it's ready for testing.

**Comment by bizley** [comment]
My email is in every repo. It's pb@human-device.com
I'll let you know when it's ready. Cheers.

**Comment by Felli** [comment]
Good to know. :+1:

**Comment by bizley** [comment]
Beta is up :)
