### ISSUE TITLE
Make it better?

### ISSUE THREAD

**Issue by bizley** [bizley/yii2-podium#20]
Reading http://habrahabr.ru/post/273615 and http://yiiframework.ru/forum/viewtopic.php?t=34676&p=176790 made me think about Podium's flaws.
- Should I do it more abstract?
- Should I move controller's logic to model in every case or maybe create some service layer for it? DefaultController's actions are really heavy...

I want to serve Podium content outside the module in 1.0 as well.

Some tips on how to make it more than "bunch of functionalities without a final developer in mind"?

**Comment by samdark** [comment]
> Should I do it more abstract?

Probably.

> Should I move controller's logic to model in every case or maybe create some service layer for it? DefaultController's actions are really heavy...

Looks like worth creating a separate layer for it.

> Some tips on how to make it more than "bunch of functionalities without a final developer in mind"?

Try to decouple it from the application as much as possible.

**Comment by bizley** [comment]
Plans for improvement before v1.0:
- Moving remaining logic from Controller layer to Model layer.
- Moving remaining logic from View layer to Model layer.
- Splitting Model layer into separated Service-like models.
- Extracting the main View parts of module into the widgets.
- Reformatting views for better theming options.
