### ISSUE TITLE
podium install not work in pretty url

### ISSUE THREAD

**Issue by hafees500** [bizley/yii2-podium#21]
podium installation not work in prtty url mode (www.example.com/podium )

it show db error message 

https://www.dropbox.com/s/mkcxbrl3q0h50dj/Screenshot%20from%202016-01-08%2018%3A39%3A50.png?dl=0

**Comment by bizley** [comment]
Please paste here you configuration file (frontend/config/main and main-local).

**Comment by hafees500** [comment]
i not add in frontend config add in common config

## common/config/main-param.php 

<?php
return [
    'bootstrap' => ['log', 'podium'],
    'components' => [
    'authManager' => [
              'class' => 'yii\rbac\DbManager', // or use 'yii\rbac\PhpManager'
        ],
        'db' => [
            'class' => 'yii\db\Connection',
            'dsn' => 'mysql:host=localhost;dbname=nordic3',
            'username' => 'root',
            'password' => 'redhat',
            'charset' => 'utf8',
             'enableSchemaCache' => true,
        ],
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            // send all mails to a file by default. You have to set
            // 'useFileTransport' to false and configure a transport
            // for the mailer to send real emails.
            'useFileTransport' => true,
        ],
    ],
    'modules' => [
    'podium' => [
        'class' => 'bizley\podium\Module',
        //'allowedIPs' => ['192.168.2.200/'], // optional
    ],
],
];

## common/config/main.php 

<?php

$config = [
    'components' => [
        'request' => [
            // !!! insert a secret key in the following (if it is empty) - this is required by cookie validation
            'cookieValidationKey' => '6nY5fRTTs_sxdHB2aI4MoMEc3hLM54nV',
        ],
    ],
];

if (!YII_ENV_TEST) {
    $config['bootstrap'][] = 'gii';
     $config['modules']['gii'] = [
        'class' => 'yii\gii\Module',
        'allowedIPs' => ['127.0.0.1', '::1', '192.168.2.*', '192.168.2.200'],
    ];
}

return $config;

**Comment by bizley** [comment]
Have you got pretty urls configured? If so paste here the configuration as well.

**Comment by hafees500** [comment]
'urlManager' => [
                'enablePrettyUrl' => true,
                'showScriptName' => false,
                 'rules' => [
                            'controller:w+/id:d+' => '<controller>/view',  
                            'controller:w+/action:w+/id:d+' => '<controller>/<action>',  
                            'controller:w+/action:w+' => '<controller>/<action>',

```
                        ],
    ],
```

.htaccess
Options +FollowSymlinks
RewriteEngine On

# deal with admin first

RewriteCond %{REQUEST_URI} ^/nordic2/(admin) 
RewriteRule ^admin/assets/(._)$ backend/web/assets/$1 [L]
RewriteRule ^admin/themes/assets/(._)$ backend/themes/assets/$1 [L]
RewriteRule ^admin/css/(._)$ backend/web/css/$1 [L]
RewriteRule ^admin/uploads/(._)$ backend/web/uploads/$1 [L]

RewriteCond %{REQUEST_URI} !^/nordic2/backend/web/(assets|css)/  
RewriteCond %{REQUEST_URI} !^/nordic2/backend/themes/(assets)/  
RewriteCond %{REQUEST_URI} ^/nordic2/(admin)  
RewriteRule ^.*$ backend/web/index.php [L]

RewriteCond %{REQUEST_URI} ^/nordic2/(assets|css)
RewriteRule ^assets/(._)$ frontend/web/assets/$1 [L]
RewriteRule ^css/(._)$ frontend/web/css/$1 [L]
RewriteCond %{REQUEST_URI} !^/nordic2/(frontend|backend)/themes/ 
RewriteCond %{REQUEST_URI} !^/nordic2/(frontend|backend)/web/uploads/
RewriteCond %{REQUEST_URI} !^/nordic2/(frontend|backend)/web/(assets|css)/
RewriteCond %{REQUEST_URI} !index.php
RewriteCond %{REQUEST_FILENAME} !-f [OR]
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ frontend/web/index.php

**Comment by bizley** [comment]
1. The urlManager rules seems to be wrong. Please read the Yii 2 guide's section [Routing and URL Creation](http://www.yiiframework.com/doc-2.0/guide-runtime-routing.html) to fix this.
2. It looks like you have got the advanced template accessible from one domain name. For the proper configuration follow guides like [Yii 2 Advanced Application. One Domain Configuration](https://github.com/mickgeek/yii2-advanced-one-domain-config).
3. You set authManager component. If you want Podium to use it instead of creating its own component set `'rbacComponent' => 'inherit',` in the `podium` module configuration array.

I'm closing this issue now. Feel free to reopen it in case there are some problems with Podium in pretty url mode.
