### ISSUE TITLE
Forums Installer

### ISSUE THREAD

**Issue by Felli** [bizley/yii2-podium#22]
It would be really nice to have an installer provided to those wishing not to use composer, as it stands there are a lot of people who wouldn't know how, or what to do when it comes to composer so opening up to other options is necessary for this. :smiley:

**Comment by bizley** [comment]
Hmm... How to approach this?
Podium depends on other vendors so the package needs to have them already provided. And updated every time vendor updates its library.
The only thing I can think of is to prepare standalone version based on the basic template with everything preinstalled (and without the support to add other Yii extensions to the version prepared like this) as an addition to the standard composer based module installation.

**Comment by Felli** [comment]
Hmm that does sound like somewhat of a problem, I would think going along the same approch as [HumHub](https://github.com/humhub) would be somewhat necessary for a installer to be added, the sad thing about doing this is a lot of rewriting will most like have to be done... Either way I'd love to have a way of using Podium & HumHub as a whole, both are done in Yii2 and if I can say both are very promising for Yii framework users. :smiley:

**Comment by bizley** [comment]
From `0.2` Podium will be served as zip file in addition to composer installation.

Package will include:
- Latest Yii 2 basic template.
- Preconfigured Podium.
- Preinstalled latest vendor packages.

Zip file will not be updated between releases (excluding bug cases).
