### ISSUE TITLE
Install won't run

### ISSUE THREAD

**Issue by supergoudvis116** [bizley/yii2-podium#23]
'Unable to resolve the request "site/podium/install/import" is the error I get from the log. Everything seems ok so im kind of lost.

on screen it just shows : There was a major error during installation...

**Comment by supergoudvis112** [comment]
Giving me a major error occured without giving me the line where it crashes. Run works but than when you call the AJAX it crashes

**Comment by bizley** [comment]
Have you got 0.1 version? I've just installed it on clean basic app without problem.
There is an installation problem on 0.2 but it's not released yet so please don't report issues on 0.2.

**Comment by supergoudvis116** [comment]
Its on the 0.1 all though I use the advanced template. Its clean with pretty url enabled everything else is working fine.

**Comment by bizley** [comment]
I've just finished installing it on advanced template. All good.
Please provide me your configuration file, I'll try to reproduce it.

**Comment by supergoudvis116** [comment]
http://pastebin.com/iFeJFTJT

I'll give you access to my server if you like as well. Contact me on my skype (send you a request already) if you need further details. Thanks for helping already!

**Comment by bizley** [comment]
It's because of this urlManager rule

```
'<action:.*>'=>'site/<action>'
```

It's hijacking the installation import url. Remove it or make it less general.
