### ISSUE TITLE
There was a major error during installation...

### ISSUE THREAD

**Issue by dev6** [bizley/yii2-podium#24]
Getting this error when trying to install this module in yii 2.0.6

Any help on how it can be fixed as the module doesn't give any log output of error?

**Comment by bizley** [comment]
Sure thing. There should be app.log in runtime folder. Check this out and let me know. If it's empty provide your configuration file and I'll try to reproduce it.

**Comment by dev6** [comment]
Fixed this error by removing the extended lines in the configuration file for this module. This part of the installation wiki didn't work for me and removing the extra four lines started the installation procedure as expected.

`'podium' => [
    'class' => 'bizley\podium\Module',
    'allowedIPs' => ['xxx.xxx.xxx.xxx'] // optional
    'userComponent' => 'inherit',
    'rbacComponent' => 'inherit', // optional
    'adminId' => 1, // optional
    'userPasswordField' => 'user_pass_hash', // optional
],
`

**Comment by bizley** [comment]
Glad to hear it. It looks like I need to add additional conditions for extra options.
This might sound like a stupid question but did you replace the 'xxx.xxx.xxx.xxx' and 'user_pass_hash' with actual values? And have you got the RBAC component in your main configuration file?
