### ISSUE TITLE
Plural not working in podium

### ISSUE THREAD

**Issue by supergoudvis116** [bizley/yii2-podium#25]
First I want to say thank you for this awesome piece of software looks modern and clean. After installing I already found out that plural wasn't working but I just assumed it was Yii2 who needed the ICU 49 + but even after updating my OS to ubuntu 15.04 and installing php 5.6 with intl (ICU 52) it wont load the plural of Podium. Even though the plural works on home pages. Is it a common problem or do I have some spooky things going on?

**Comment by bizley** [comment]
Cheers.
Could you point me to the exact problematic message?

**Comment by supergoudvis116** [comment]
At the install none of the messages gets translated. I am just getting {{%podium_user}}  for example. This is not a big deal but if im logged in and go to podium, open a forum it will crash on a foreach User->Each() from the bizley\podium\widgets\Readers::run() .

`$users = Activity::find()->joinWith(['user'])->where($conditions)->params([':url' => $url . '%']);
        foreach ($users->each() as $user) {
            $out .= $user->user->podiumTag . ' ';
        }` at rulenumber 78 till 81 it will send the conditions for the query with the {{}} around it.

`[['{{%podium_user_activity}}.anonymous' => 0], ['is not', 'user_id', null], yii\db\Expression, ['>=', '{{%podium_user_activity}}.update...', 1463740583], ...], '<span class="string" title="[&lt...')`

this is happening in every query related to it think about unread posts etc etc.

Hope I gave you enough information to work with :+1:

**Comment by bizley** [comment]
What you are describing is not a message to translate - it's the name of DB table i.e. `{{%podium_user}}` will output `podium_user` table name if you configure your DB connection without table prefix (and `yii2_podium_user` if prefix is set to `yii2_`).
Did installation process finish successfully? Please check your DB connection, DB structure and app logs and let me know.

**Comment by supergoudvis116** [comment]
Database is fully functional and the installation finished perfectly fine. I can even add and go into forums when im a guest but as soon as I am logged in things get messed up. 

http://snw.eu-sf3.com/podium/

I suggest you create an account, login and see for yourself to see what happens :p

**Comment by bizley** [comment]
There was an error in Reader class, fixed now in dev-master version currently.
Cheers!

**Comment by supergoudvis116** [comment]
I think you created another error whilst fixing this one, if you now aren't logged in and open a thread it will give you an error as well 
           `$access = Yii::$app->authManager->checkAccess($user->id, $permissionName, $params);`

is where the error is getting created. probably because $user returns NULL at $user = static::findme(); at vendor/bizley/podium/models/User.php

**Comment by bizley** [comment]
Fixed, thanks!
