### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#28]
Do you need russian translation? I can do it :)

**Comment by bizley** [comment]
Yes, please :)

**Comment by ekaterina-git** [comment]
Ok! Then after I complete translation and check it, I will create a pull request.

**Comment by ekaterina-git** [comment]
So you [speak Russian](https://github.com/bizley/yii2-podium/issues/20#issue-124978608)? :D Since you could read habr article :)

**Comment by bizley** [comment]
Just a bit, I still need a help from Google Translate.

**Comment by ekaterina-git** [comment]
That's OK, I just found it a bit funny :)

**Comment by bizley** [comment]
Why is that? :smile:

**Comment by ekaterina-git** [comment]
I don't know :) Doesn't matter anyways :D
So I'd completed the translation but I encountered some problems while trying to install Podium on my local website :( I think I'll check my translation properly later, after work, but it looks okay at the moment.

**Comment by bizley** [comment]
Try to install `dev-master` version. Let me know if there are any problems.

**Comment by ekaterina-git** [comment]
Okay, I will, thanks!

**Comment by bizley** [comment]
Closed via #29
