### ISSUE TITLE
Make merging posts configurable (for different groups/users)

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#33]
How about making merging posts configurable for different groups (roles)? 
Such feature is presented in some boards I know and I think it's pretty useful.

UPD or at least maybe give admins permission to choose whether they want to merge their post with the previous one or not.

**Comment by ekaterina-git** [comment]
Also I thought that it would be better not to merge posts if the previous one was posted, for example, more than one week ago? And this 'more than one week ago' should also be configurable. What do you think? I can try and do this :)

**Comment by bizley** [comment]
I'll make it an option for administrator to choose. I prefer to merge posts but you are right, it should be optional.

**Comment by bizley** [comment]
New option added (some translation strings changed in update process).
