### ISSUE TITLE
Console error

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#37]
When I called 'php yii podium/queue/run' from command line (I was in the correct directory), I got 

> Error: Unknown command "podium/queue".

I edited console.php  as you said in installation wiki

**Comment by bizley** [comment]
Right. Forgot one thing in wiki.

In console configuration add `'podium'` value in the `'bootstrap'` key like:

```
'bootstrap' => ['log', 'podium'],
```

Should be ok with it.

**Comment by ekaterina-git** [comment]
Yes, that worked, thanks
