### ISSUE TITLE
Merge reply with post in case of the same author (default on)

### ISSUE THREAD

**Issue by osnwach** [bizley/yii2-podium#39]
Bizley, thanks so much for Podium. It is quite great ! and I am really enjoying it !! 

Please I installed version 0.1. and I can't find the feature "Merge reply with post in case of the same author (default on)". It is supposed to be in POSTS section of 'PODIUM SETTINGS'

Please how can I disable this Feature, since I don't want it that way ?

Thanks !

**Comment by ekaterina-git** [comment]
This feature became optional only since #33 (and in version 0.2)
However, you can disable this manually, making changes in Podium source

**Comment by osnwach** [comment]
Thanks Katenkka ! So it will come with version 0.2

But now I have version 0.1, please which files do I need to adjust & which lines ?

Warm Regards from me!

**Comment by ekaterina-git** [comment]
The simpliest way is to add 
`1 == 0 &&`
to [this condition](https://github.com/bizley/yii2-podium/blob/4e848cf6052de08e77d521c9102aad0aeaf8c44b/controllers/DefaultController.php#L1313)

**Comment by bizley** [comment]
Haxxor! :boom: :P Yup, do it like that for now. Sorry for this delay with 0.2, busy time right now. I hope to release 0.2 before end of September.

**Comment by ekaterina-git** [comment]
:laughing: Yeah, I sometimes do such conditions if I don't want to change source a lot) This way you can still see what the original condition was :)

**Comment by osnwach** [comment]
Katenkka, Please how can I insert an image or a hyperlink in my post ?

Presently when I click on the image icon in the WYSIWYG editor, it shows a dialog box, but I can't insert image ?

Please how can I insert image in the post ?

Thanks in advance !

**Comment by ekaterina-git** [comment]
Hi again, @osnwach . I'm sorry, I didn't try it yet in Podium, you'd better wait for @bizley to answer

**Comment by bizley** [comment]
@osnwach in the future please create a new issue in case of a new problem. As for the images - go to the thread you want to reply in, click `New Reply` button (quick reply editor hasn't got images button) and on the next page click the last icon on the right side in the editor - this popup will appear where you can type image URL address.
