### ISSUE TITLE
no access redirects to hardcoded "/podium/" url

### ISSUE THREAD

**Issue by dakipro** [bizley/yii2-podium#58]
Hi, i tried playing with the module and it looks promising. I noticed one small thing, when I mark off f.eks. Allow guests to list members, if a guest visits some url it would redirect to "/podium/forum/index" .
It would give flash error message that you need to login. 
Thing is that I installed module as a "support" so correct redirect would be "/support/forum/index" 
Or is it stored somewhere in database that was set during the installation?

**Comment by bizley** [comment]
You are right, I totally forgot about custom module IDs. Thank you for pointing that out.
I will fix this in next release.
