### ISSUE TITLE
Wysiwyg editor replace

### ISSUE THREAD

**Issue by bizley** [bizley/yii2-podium#6]
Zelenin's Summernote is no longer maintained. Need new editor.

**Comment by bizley** [comment]
I've replaced CKEditor with Trumbowyg. CKE is too complicated for this module.
TW is a bit old and hasn't got all the features I need but still better - looking forward to see TW v2.0 with modern semantic.
I would love to use Froala but it's not free.

**Comment by Felli** [comment]
@bizley-code good choice going with Trumbowyg, but I'm wondering why you haven't tried out [Quill](https://github.com/quilljs/quill//) or [NicEdit](http://nicedit.com/) if the normal Wysiwyg is too complicated?

**Comment by bizley** [comment]
I don't like the look of NE.
But I remember checking Quill... and I went for TW... and I don't remember why... Strange.
Quill looks nice, I'll give it another try. Cheers.

**Comment by Felli** [comment]
Good to hear, as Quill (In my honest opinion) would be a better choice over Trumbowyg, but I think the biggest difference between them is that Trumbowyg is lighter and Quill is heavier?

**Comment by bizley** [comment]
I hope I don't preach to the converted here but I've started working on Quill extension for Yii 2 (is there one already? I cannot find it). Quill has got terrible documentation btw.

**Comment by Felli** [comment]
At the moment the only one that I could find that is somewhat of a Quill extension would be for React  which is found [here](https://github.com/zenoamaro/react-quill), but don't quote me on this.

**Comment by bizley** [comment]
My implementation of Quill is ready :) Check it out https://github.com/bizley-code/yii2-quill
