### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by join2web** [bizley/yii2-podium#60]
Hello. I had a problem during installation.

`SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
The SQL being executed was: ALTER TABLE `podium_user_activity` ADD INDEX `idx-user_activity-url` (`url`)`

Mysql version 10.1.17-MariaDB

**Comment by bizley** [comment]
Apparently setting index on column varchar(1024) doesn't work on some systems which I did not know.
In next release I will remove this index and for a quick solution now you can remove this part

```
[
    'table' => 'user_activity',
    'call'  => 'addIndex',
    'name'  => 'url',
    'cols'  => ['url'],
],
```

from `\vendor\bizley\podium\src\maintenance\steps\install.php` and run installation again.
