### ISSUE TITLE
Cache issue in console

### ISSUE THREAD

**Issue by vishuB** [bizley/yii2-podium#62]
In Podium 0.5 beta
when run below cronjob

`php /var/www/html/rnd/podium-rnd/yii podium/queue/run`

Then i will get below error log

````
2016-11-29 11:53:12 [-][-][-][error][bizley\podium\PodiumConfig::fromCache] [
         'msg' => 'Unknown component ID: podium_cache',     
         'model' => null, 
]
````
This is my console config

````
$config = [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'podium'],
    'controllerNamespace' => 'app\commands',
    'components' => [
        'mailer' => [
	     'class' => 'yii\swiftmailer\Mailer',
	     'useFileTransport' => false,
	     'transport' => [
		'class' => 'Swift_SmtpTransport',
		'host' => 'smtp.gmail.com',
		'username' => 'xyz@gmail.com',
		'password' => 'xyz',
		'port' => '587',
		'encryption' => 'tls',
	     ],
	],
    ],
    'modules' => [
	'podium' => [
              'class' => 'bizley\podium\Podium',
              'cacheComponent' => 'cache',
	],
    ],
    'params' => $params,
];
````

**Comment by bizley** [comment]
Wait... at Gitter you provided configuration without `cacheComponent`. I need to double check but the configuration with `cacheComponent` set to `cache` and no `cache` component configured must give you error.

I thought there is no `cacheComponent` set and you still get error, that is why I ask to create this issue.
Remember that console and web config is separated in "basic" app (at least as default implementation) so `cache` set in web part is not present in console part.

Anyway I will verify this and let you know.

**Comment by bizley** [comment]
I confirm this is the case I've mentioned earlier. Unrecognised `cache` component adds error log.

But there is another bug here - having no cache should not end returning no config value - cache needs to be skipped here.

**Comment by bizley** [comment]
I keep this open untill 0.6.

**Comment by bizley** [comment]
0.6 released.
