### ISSUE TITLE
Usability: do not require password to change timezone

### ISSUE THREAD

**Issue by samdark** [bizley/yii2-podium#65]
At http://bizley.pl/podium/profile/details it's currently required to enter password in order to change timezone. There's nothing bad in allowing changing it without entering password.

**Comment by bizley** [comment]
You are right, I will move it to Forum Details.

**Comment by bizley** [comment]
Time zone selection is now in Forum Details. The same for the option to browse forum anonymously.  
Database schema has been changed so after update timezone goes back to default UTC and anonymous flag goes back to unchecked.

**Comment by bizley** [comment]
I keep this open untill 0.6.

**Comment by bizley** [comment]
0.6 released.
