### ISSUE TITLE
Unknown properties

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#67]
forum/admin/contents:

> Unknown Property – yii\base\UnknownPropertyException

> Setting unknown property: bizley\podium\widgets\quill\QuillFull::style

Also there's a bug in \bizley\podium\models\db\UserActiveRecord::validatePassword  (Podium::FIELD_PASSWORD doesn't exist anymore)

**Comment by bizley** [comment]
Thanks!

**Comment by bizley** [comment]
I keep this open untill 0.6.

**Comment by bizley** [comment]
0.6 released.
