### ISSUE TITLE
Not unique index name

### ISSUE THREAD

**Issue by ekaterina-git** [bizley/yii2-podium#68]
Yesterday I finally managed to install the latest version of Podium with DbManager :champagne: 
But while installing I came across the problem that index `idx-auth_item-type` was already presented in my DB. It got there during yii2-user package installation so I had to add a migration to my main app that renamed existing index to something like `blah-blah-idx-auth_item-type`.
Do you have any idea how to avoid those cases?
Or maybe I should create an issue in amnah/yii2-user repository?

**Comment by Katenkka** [comment]
Or maybe I should create an issue in @amnah/yii2-user ?

**Comment by bizley** [comment]
Have you created table for `DbManager` before installing Podium?

**Comment by ekaterina-git** [comment]
Yes. Changed the configuration to
` 'authManager' => [
        'class' => 'yii\rbac\DbManager',
    ],`, ran a DbManager migration, then installed Podium.

**Comment by ekaterina-git** [comment]
I'm sorry, I wrote 

> It got there during yii2-user package

but really it was during DbManager migration run, of course

**Comment by bizley** [comment]
Argh... Right, I'm using table names without prefix for index names which can lead to collision. Fix on the way.

**Comment by ekaterina-git** [comment]
Thanks! Well, DbManager migration doesn't use prefixes either :wink:

**Comment by bizley** [comment]
From now on indexes and foreign keys name parts with table names include `podium` prefix. Unfortunately there are so many of them I decided not to include the change in Podium update so only fresh installation is affected.

**Comment by bizley** [comment]
I keep this open untill 0.6.

**Comment by bizley** [comment]
0.6 released.
