### ISSUE TITLE
Get error when send message

### ISSUE THREAD

**Issue by vishuB** [bizley/yii2-podium#75]
I got error when send message without `member`. show below image

![aaaaa](https://cloud.githubusercontent.com/assets/13677102/21453178/9e47b030-c932-11e6-86a1-1f9958596780.png)

And click `send message` button then give below error.

![bbbbb](https://cloud.githubusercontent.com/assets/13677102/21453196/c86ac6f4-c932-11e6-8e88-11f37a5b6d25.png)

**Comment by bizley** [comment]
I keep this open untill 0.6.

**Comment by bizley** [comment]
0.6 released.
