### ISSUE TITLE
It's hard to set focus on new thread content

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-podium#79]
When creating a new thread:
click on middle (vertical) of content field do nothing - because area below a first line (div.ql-editor.ql-blank) don't set focus.

I believe it's worth to fix that.

Firefox 50.1

**Comment by bizley** [comment]
I've fixed this by adding forced focus on click for the yii2-quill editor. Just `composer update` Podium to fetch new yii2-quill.
