### ISSUE TITLE
Delete button on Message inbox not working

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-podium#84]
1. Go to: Messages -> Messages Inbox (or Sent Messages)
2. Click Delete button on message -> nothings happens
3. Click View message -> here delete button works (show modal popup)

Firefox 50.1

**Comment by bizley** [comment]
This has been fixed in e7a4f42e29a0729aa754faa56a9e98a12524e221 - ready in 0.6.
Thanks.
PS. I will leave tickets opened untill release now.

**Comment by bizley** [comment]
0.6 released.
