### ISSUE TITLE
Beta test

### ISSUE THREAD

**Issue by cv65kr** [bizley/yii2-podium#9]
Can You realease the beta test of this module?

**Comment by bizley** [comment]
As soon as it's ready. It's alpha stage now - few things are still not right.
I'll let everybody know, no worries.

**Comment by cv65kr** [comment]
Maybe can You show few screenshots of module. 
I'm very interested.
Greetings!

**Comment by bizley-code** [comment]
There is this work-in-progress online version at bizley.pl 
You can as well run composer require bizley/podium "dev-master" for your app.
Please remember that this version isn't suitable for testing and calling issues yet ;)

**Comment by bizley** [comment]
Beta is up!
You are all welcome to test it and report any issues and / or suggestions :)
Cheers.
