### ISSUE TITLE
Links icon in Quill don't work

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-podium#91]
Here: https://quilljs.com/playground/#form-submit
when select some text in post and click "ql-link" icon - "Enter link" dialog shows.
In Podium nothings happens.
BTW, click on "ql-video" (in Podium) also do nothing.

**Comment by bizley** [comment]
Seems that [updating to Quill 1.2.0](https://github.com/bizley/yii2-quill/releases/tag/2.2) fixed the problem.
