### ISSUE TITLE
Installation too fast

### ISSUE THREAD

**Issue by triboe** [bizley/yii2-podium#97]
When I tried installation on shared hosting, table generation stopped in the middle (something like "podium_config not found"). Inserting a sleep() statement helped.

**Comment by bizley** [comment]
This is unusual. Queries are processed one after another so installation waits until previous query finishes before starting new one.

Could you give me more information about this? Maybe how to reproduce it? Error log and so on.

**Comment by triboe** [comment]
Podium 0.6 on Yii 2.0.10, installed by composer, One.com Starter hosting, podium/install/run.

`2017-02-04 22:50:08 [<my_ip>][-][-][error][bizley\podium\PodiumConfig::getStored] [
    'msg' => 'SQLSTATE[42S02]: Base table or view not found: 1146 Table \'<mydomain>.podium_config\' doesn\'t exist
The SQL being executed was: SELECT * FROM `podium_config`',
    'model' => null,
]
    in /customers/5/4/5/<mydomain>/httpd.www/AppYii206/Yii2/vendor/bizley/podium/src/log/Log.php:54
    in /customers/5/4/5/<mydomain>/httpd.www/AppYii206/Yii2/vendor/bizley/podium/src/PodiumConfig.php:166
    in /customers/5/4/5/<mydomain>/httpd.www/AppYii206/Yii2/vendor/bizley/podium/src/PodiumConfig.php:146
`

With this addition installation succeeded (I didn't try 1 second)
```
        sleep(2); // TRi

        $this->table = $this->steps[$currentStep]['table'];
        $result = call_user_func_array([$this, $this->steps[$currentStep]['call']], $this->steps[$currentStep]['data']);

```

**Comment by bizley** [comment]
This error should not stop installation (at least I think so). I will modify the code to not trigger this into logs during installation because people think something is wrong.

Let me make some additional tests and get back to you in few hours.

**Comment by triboe** [comment]
I checked what was in the db after the installation stopped. Last table generated seemingly was podium_config. At least it did not continue.

**Comment by bizley** [comment]
I can not reproduce it. Please try again with new 0.7 installation and let me know if there are any errors (log, on screen etc.).

**Comment by bizley** [comment]
Feel free to open this issue in case this happen again.
