### ISSUE TITLE
Unknown column "new_post_at" Database Exception

### ISSUE THREAD

**Issue by tomaszkane** [bizley/yii2-podium#98]
1. go to forum
2. choose "Show only: -> New Posts" filter
3. got
`Database Exception – yii\db\Exception
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'new_post_at' in 'where clause'
The SQL being executed was: SELECT * FROM podium_thread_view WHERE (((user_id=1) AND (new_last_seen < new_post_at)) OR (user_id IS NULL)) AND (thread_id=4)`

Bug is in `/models/Thread.php:81`.

**Comment by bizley** [comment]
Could you give me more details about this? In every piece of code similar query can be found table used is `podium_thread` and `podium_thread_view` is joined...

**Comment by bizley** [comment]
The current filter query is wrong and I'm fixing it right now but it's different from the one in your exception anyway.

**Comment by bizley** [comment]
Looks like modified query ends with exception like yours after all.

**Comment by bizley** [comment]
Fixed by bb8f44a69e659ab958e99659770800cf8a1814dc
