### ISSUE TITLE
Theming Possible?

### ISSUE THREAD

**Issue by jcshep** [bizley/yii2-podium#99]
Is it possible to theme this module? Been trying using the instructions [here](http://www.yiiframework.com/doc-2.0/guide-output-theming.html#theming-modules)  but not having any luck.

**Comment by bizley** [comment]
Podium views are definitely to be rewritten because these are too complex with business logic mixed up with html. Nevertheless theming should work because this is simply just using different files to generate the  output of the same source.

**Comment by jcshep** [comment]
Thanks! I was able to get it working by copying the entire views folder into my theme and adding the viewPath in the theme configuration.

Great job on the module.

**Comment by ciapistess** [comment]
@jcshep Ahem ... I'm a bit late  ... however ...
may I ask you, please, to be more precise? Namely to write here your configuration for 
'view' => [ 'theme' => [ ....
and the name of the destination folder for the copied views.

I tried a lot of combinations but no luck ...
Thanks

**Comment by ciapistess** [comment]
Well, after some deep debugging I eventually found a solution:
```
'view' => [
    'theme' => [
        'basePath' => '@app/themes/ecn-theme',
        'pathMap' => [
          '@podium/views' => '@app/themes/ecn-theme/modules/podium', 
        ],
    ],

with
@podium/views/* copied into @app/themes/ecn-theme/modules/podium/
```

Honestly I believe the explanation in the official Yii doc-2.0, at least regarding modules, is misleading ...

Actually, my main problem was in the initial installation of [yee-cms](https://github.com/yeesoft/yii2-yee-cms/blob/master/frontend/config/main.php), which uses a local Theme class.

Thanks anyway.
